<?php
/**
 * Copyright © O2TI. All rights reserved.
 *
 * @var \O2TI\SocialLogin\Block\Providers $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isModuleEnabled()): ?>
<div class="block-social-login" data-bind="scope:'providers'">
   <!-- ko template: getTemplate() -->
   <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
   "*": {
       "Magento_Ui/js/core/app": {
           "components": {
               "providers": {
                   "component": "O2TI_SocialLogin/js/view/buttons",
                   "template": "O2TI_SocialLogin/social-login",
                   "data": <?= /* @noEscape */ $block->getSocialConfigJson() ?>
               }
           }
       }
   }
}
</script>
<?php endif; ?>